spring:
  init:
    mode: always
  datasource:
    url: jdbc:mysql://linkdbserver.cvultwfb8mhe.ap-northeast-2.rds.amazonaws.com:3306/LINK?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: rkdcks12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql : true
logging:
  level:
    me.silvernine: DEBUG
jwt:
  header: Authorization
  secret: Z2J2ZmRiamRma3N2amtmdmplZmtzZGhqZXJrbmZqZ2VrcmZuamxyd2VqcmV3NjVrandlcjZod2VrNmVscjhmdnlkbGlzOHZ1bHJlbzM0OXQ5NHM4OXczNTc4M3dheWh0d2E4ZnczYTg5MzQ3MjM5ODRyaG5sZHNqaGxpc2tkenZqbGRzaXUzbDRpcmhlZnN6ZnNlamhkZmtjc2hqZGNremh4amN2a3hjbG5qdnJuZWprbHVyNWozNGxrcnVma2xzZHpmN3NkZnk4bDM3dzQ4Mzc0ODkyMzR1ZGZoemlzenVodmxpZDh2czdkemM4NjM3MjhyaWwyeTM4cjMyZHk4cWM4cTIzbHJ4OGx6OHIzeXhsYXdyMjM4OXI2MjM4NzlscjNuODJjOXJhbnkzODJjcmx5bDgyaWNyOG4y
  token-validity-in-seconds: 86400 # 시간초 유효시간